package dossiers

// Les dossiers « verticaux » : une politique publique suivie par ses missions
// budgétaires (justice, culture, recherche et enseignement supérieur, logement et
// territoires, outre-mer, action extérieure, sport et vie associative, fonction
// publique, économie et participations de l'État, France 2030, agriculture).
//
// Chaque dossier reçoit le même socle : les crédits par programme du projet de
// loi de finances (core.budget_programme, via ref.dossier_mission), les textes
// qui fondent la politique (relus dans le Journal officiel chargé) et les
// constats du rapporteur spécial de la commission des finances du Sénat sur le
// projet de loi de finances pour 2026 (« L'essentiel sur… », relu au chargement).

// senat : un constat de la synthèse d'un rapport spécial du Sénat sur le PLF
// 2026. annexe est le numéro d'annexe du rapport général n° 139 (2025-2026) :
// « 317 » pour la Justice, « 35-1 » pour le logement.
func senat(id, dossier, section, annexe, date, personne, mission, intitule, constat string, attendus ...string) Fait {
	return Fait{ID: id, Dossier: dossier, Section: section, Theme: "rapports parlementaires", Type: "EVALUATION", Date: date,
		Auteur:   "Sénat, commission des finances (rapport spécial sur la mission « " + mission + " », projet de loi de finances pour 2026)",
		Personne: personne, Intitule: intitule, Constat: constat,
		URL:     "https://www.senat.fr/rap/l25-139-" + annexe + "/l25-139-" + annexe + "-syn.pdf",
		Qualite: "OFFICIEL", Attendus: attendus}
}

const (
	dJustice   = "justice-donnees"
	dCulture   = "culture-donnees"
	dRecherche = "recherche-enseignement-superieur-donnees"
	dLogement  = "logement-territoires-donnees"
	dOutreMer  = "outre-mer-donnees"
	dExterieur = "action-exterieure-donnees"
	dSport     = "sport-vie-associative-donnees"
	dFonction  = "fonction-publique-donnees"
	dEconomie  = "economie-participations-donnees"
	dFrance30  = "france-2030-donnees"
	dAgri      = "agriculture-donnees"
)

func init() {
	missions = append(missions,
		Mission{dJustice, "Justice", `^Justice$`},
		Mission{dCulture, "Culture", `^Culture$`},
		Mission{dCulture, "Médias, livre et industries culturelles", `^Médias, livre et industries culturelles$`},
		Mission{dCulture, "Audiovisuel public (compte de concours financiers)", `^(Avances à l'audiovisuel public|Audiovisuel public)$`},
		Mission{dRecherche, "Recherche et enseignement supérieur", `^Recherche et enseignement supérieur$`},
		Mission{dLogement, "Cohésion des territoires", `^Cohésion des territoires$`},
		Mission{dOutreMer, "Outre-mer", `^Outre-mer$`},
		Mission{dExterieur, "Action extérieure de l'État", `^Action extérieure de l'État$`},
		Mission{dExterieur, "Aide publique au développement", `^Aide publique au développement$`},
		Mission{dSport, "Sport, jeunesse et vie associative", `^Sport, jeunesse et vie associative$`},
		Mission{dFonction, "Transformation et fonction publiques", `^Transformation et fonction publiques$`},
		Mission{dEconomie, "Économie", `^Économie$`},
		Mission{dEconomie, "Participations financières de l'État (compte d'affectation spéciale)", `^Participations financières de l'État$`},
		Mission{dFrance30, "Investir pour la France de 2030", `^Investir pour la France de 2030$`},
		Mission{dFrance30, "Plan de relance", `^Plan de relance$`},
		Mission{dAgri, "Agriculture, alimentation, forêt et affaires rurales", `^Agriculture, alimentation, forêt et affaires rurales$`},
		Mission{dAgri, "Développement agricole et rural (compte d'affectation spéciale)", `^Développement agricole et rural$`},
	)

	termes = append(termes,
		Terme{dJustice, "aide juridictionnelle", `aide juridictionnelle`},
		Terme{dJustice, "surpopulation carcérale", `surpopulation (carcérale|pénitentiaire)|surencombrement carcéral`},
		Terme{dJustice, "moyens de la justice", `(moyens|budget) de la justice`},
		Terme{dCulture, "audiovisuel public", `audiovisuel public`},
		Terme{dCulture, "patrimoine", `monuments historiques|patrimoine culturel`},
		Terme{dCulture, "pass Culture", `pass.culture`},
		Terme{dCulture, "spectacle vivant", `spectacle vivant`},
		Terme{dRecherche, "Parcoursup", `parcoursup`},
		Terme{dRecherche, "loi de programmation de la recherche", `programmation de la recherche`},
		Terme{dRecherche, "précarité étudiante", `précarité étudiante`},
		Terme{dLogement, "logement social", `logements? sociaux|logement social`},
		Terme{dLogement, "aides personnalisées au logement", `\mapl\M|aides? personnalisées? au logement`},
		Terme{dLogement, "hébergement d'urgence", `hébergement d.urgence`},
		Terme{dOutreMer, "outre-mer", `outre-mer|ultramarin`},
		Terme{dOutreMer, "vie chère", `vie chère`},
		Terme{dExterieur, "aide publique au développement", `aide publique au développement`},
		Terme{dExterieur, "diplomatie", `diplomatie`},
		Terme{dSport, "service civique", `service civique`},
		Terme{dSport, "service national universel", `service national universel|\msnu\M`},
		Terme{dSport, "vie associative", `vie associative`},
		Terme{dFonction, "fonction publique", `fonction publique`},
		Terme{dFonction, "point d'indice", `point d.indice`},
		Terme{dEconomie, "participations de l'État", `participations? (financières )?de l.état|agence des participations`},
		Terme{dEconomie, "réindustrialisation", `réindustrialisation`},
		Terme{dFrance30, "France 2030", `france 2030`},
		Terme{dFrance30, "plan de relance", `plan de relance|france relance`},
		Terme{dAgri, "EGalim", `egalim`},
		Terme{dAgri, "politique agricole commune", `politique agricole commune`},
		Terme{dAgri, "souveraineté alimentaire", `souveraineté alimentaire`},
	)

	faits = append(faits,
		// Justice.
		loiArt("lopj-2023-programmation", dJustice, "CADRE", "2023-11-20", "Parlement (loi n° 2023-1059 d'orientation et de programmation du ministère de la justice 2023-2027)",
			"Programmation 2023-2027 : 10 000 emplois supplémentaires, dont 1 500 magistrats et 1 800 greffiers",
			"L'article 1er fixe la trajectoire des crédits du ministère hors pensions et les créations nettes d'emplois à 10 000 équivalents temps plein d'ici à 2027, dont 1 500 magistrats et 1 800 greffiers.",
			"JORFTEXT000048430512", "1", "fixées à 10 000 équivalents temps plein d'ici à 2027, dont 1 500 magistrats et 1 800 greffiers supplémentaires"),
		loi("lpj-2019-programmation", dJustice, "CADRE", "2019-03-23", "Parlement (loi n° 2019-222)",
			"La programmation précédente : 2018-2022",
			"Loi de programmation et de réforme pour la justice qui a précédé celle de 2023.",
			"JORFTEXT000038261631", "de programmation 2018-2022 et de réforme pour la justice"),
		senat("senat-justice-cepej-2026", dJustice, "ENJEUX", "317", "2025-11-19", "antoine-lefevre", "Justice",
			"11,3 juges professionnels pour 100 000 habitants, contre une médiane européenne de 17,6",
			"Le rapporteur spécial rapporte les données de la Commission européenne pour l'efficacité de la justice (CEPEJ) : le nombre de juges professionnels est passé de 10,7 à 11,3 pour 100 000 habitants entre 2012 et 2022, loin de la médiane européenne de 17,6, et les délais de traitement sont supérieurs à la moyenne européenne.",
			"reste éloigné de la médiane européenne qui est de 17,6"),
		senat("senat-justice-lopj-2026", dJustice, "CONTROLE", "317", "2025-11-19", "antoine-lefevre", "Justice",
			"Crédits 2026 : 10 629 M€ hors pensions, légèrement sous les 10 691 M€ programmés",
			"Hors pensions et à périmètre constant, les crédits demandés pour 2026 s'établissent à 10 629 M€, un peu en deçà des 10 691 M€ de la loi de programmation ; compte tenu de ressources nouvelles, le rapporteur spécial considère la programmation respectée dans l'ensemble pour les crédits.",
			"s'établiraient à un niveau de 10 629 millions d'euros", "la loi de programmation de la justice est dans l'ensemble respectée pour ce qui concerne les crédits"),
		senat("senat-justice-places-prison-2026", dJustice, "CONTROLE", "317", "2025-11-19", "antoine-lefevre", "Justice",
			"Plan de 15 000 places de prison : 36,1 % de la cible atteinte",
			"Les maisons d'arrêt font face à une suroccupation croissante ; le plan de construction de 15 000 places n'a été atteint qu'à 36,1 % de sa cible.",
			"n'a été atteint qu'à 36,1 % de sa cible"),
		senat("senat-justice-aide-juridictionnelle-2026", dJustice, "CONTROLE", "317", "2025-11-19", "antoine-lefevre", "Justice",
			"Aide juridictionnelle : 714,2 M€, et des délais de traitement en hausse de près de moitié depuis 2017",
			"Les crédits de l'aide juridictionnelle atteignent 714,2 M€ en 2026, plus des deux tiers au-dessus de 2017 ; le délai de traitement des demandes a pourtant augmenté de près de moitié entre 2017 et 2024.",
			"714,2 millions d'euros", "le délai de traitement des demandes d'aide juridictionnelle a augmenté de près de moitié"),
		senat("senat-justice-evaluation-2026", dJustice, "CONTROLE", "317", "2025-11-19", "antoine-lefevre", "Justice",
			"Une culture de la donnée et de l'évaluation moins développée qu'ailleurs",
			"Le rapporteur spécial juge la culture de la donnée et de l'évaluation moins développée au ministère de la justice que dans d'autres administrations, et les données insuffisantes pour objectiver les coûts des frais de justice.",
			"la culture de la donnée et de l'évaluation y est manifestement moins développée que dans d'autres administrations"),

		// Culture, médias et audiovisuel public.
		loi("lcap-2016", dCulture, "CADRE", "2016-07-07", "Parlement (loi n° 2016-925)",
			"Liberté de la création, architecture et patrimoine",
			"Loi relative à la liberté de la création, à l'architecture et au patrimoine.",
			"JORFTEXT000032854341", "relative à la liberté de la création, à l'architecture et au patrimoine"),
		loi("musees-de-france-2002", dCulture, "CADRE", "2002-01-04", "Parlement (loi n° 2002-5)",
			"Les musées de France",
			"Loi relative aux musées de France.",
			"JORFTEXT000000769536", "relative aux musées de France"),
		loi("liberte-communication-1986", dCulture, "CADRE", "1986-09-30", "Parlement (loi n° 86-1067)",
			"La liberté de communication, cadre de l'audiovisuel",
			"Loi relative à la liberté de communication, qui organise notamment l'audiovisuel public.",
			"JORFTEXT000000512205", "relative à la liberté de communication"),
		loiArt("suppression-contribution-audiovisuel-2022", dCulture, "CADRE", "2022-08-16", "Parlement (loi n° 2022-1157 de finances rectificative pour 2022, article 6)",
			"Suppression de la contribution à l'audiovisuel public",
			"L'article 6 de la loi de finances rectificative pour 2022 supprime la contribution à l'audiovisuel public de la législation fiscale ; le financement passe par le budget de l'État.",
			"JORFTEXT000046186661", "6", "les mots : « et la contribution à l'audiovisuel public » sont supprimés"),
		senat("senat-culture-baisse-2026", dCulture, "CONTROLE", "37", "2025-11-13", "vincent-eble", "Culture",
			"2026, « première année de réelle baisse » des crédits de la Culture",
			"Les crédits demandés baissent de 292 M€ en autorisations d'engagement (- 7,25 %) et de 170 M€ en crédits de paiement (- 4,34 %) ; le patrimoine (programme 175) perd 18 % en autorisations d'engagement.",
			"2026 devrait être la première année de réelle baisse des crédits", "une diminution de 232 millions d'euros (- 18 %) en AE"),
		senat("senat-culture-operateurs-2026", dCulture, "CONTROLE", "37", "2025-11-13", "vincent-eble", "Culture",
			"72 opérateurs, 2,5 Md€ de budgets, et plus de 1,3 Md€ de dépenses fiscales",
			"La mission subventionne 72 opérateurs dont les budgets totalisent 2,5 Md€ ; les dépenses fiscales rattachées dépassent 1,3 Md€ en 2026, près d'un quart des crédits budgétaires.",
			"72 opérateurs sont concernés, dont le total des budgets s'élève à 2,5 milliards d'euros", "soit près d'un quart des crédits budgétaires"),
		senat("senat-audiovisuel-public-2026", dCulture, "CONTROLE", "318", "2025-10-29", "jean-raymond-hugonet", "Médias, livre et industries culturelles",
			"Audiovisuel public : 3,878 Md€ en 2026, une baisse de 13 % en volume depuis 2019",
			"Les sociétés de l'audiovisuel public recevraient 3,878 Md€ en 2026 (- 1,8 %) ; les montants ont augmenté de 169 M€ depuis 2019 mais, inflation déduite, diminué de 13 % en volume.",
			"une diminution en volume de 13 %"),
		senat("senat-radios-locales-2026", dCulture, "CONTROLE", "318", "2025-10-29", "jean-raymond-hugonet", "Médias, livre et industries culturelles",
			"Fonds de soutien aux radios associatives quasiment divisé par deux",
			"Les crédits du Fonds de soutien à l'expression radiophonique seraient quasiment divisés par deux en 2026, à 19,5 M€ ; les aides à la presse écrite baissent de 5,8 %, à 178,29 M€.",
			"19,5 millions d'euros", "178,29 millions d'euros"),
		senat("senat-culture-frequentation-2026", dCulture, "SITUATION", "37", "2025-11-13", "vincent-eble", "Culture",
			"44 millions de visiteurs dans les musées et monuments nationaux en 2024 ; 65 millions de spectateurs",
			"Selon les chiffres du ministère repris par le rapport, les opérateurs du patrimoine (programme 175) ont accueilli 44 millions de visiteurs en 2023 et en 2024 ; le spectacle vivant a compté 65 millions de spectateurs et 2,4 Md€ de recettes en 2024.",
			"44 millions", "65 millions de spectateurs et une recette de 2,4 milliards d'euros en 2024"),

		// Recherche et enseignement supérieur.
		loiArt("lpr-2020-objectifs", dRecherche, "CADRE", "2020-12-24", "Parlement (loi n° 2020-1674 de programmation de la recherche pour les années 2021 à 2030)",
			"Programmation de la recherche 2021-2030 : 3 % du PIB en recherche et développement",
			"L'article 1er fixe l'objectif de porter la dépense intérieure de recherche et développement à au moins 3 % du PIB, dont au moins 1 % pour les administrations ; l'article 2 programme les crédits des programmes 172, 193 et 150 jusqu'en 2030.",
			"JORFTEXT000042738027", "1", "à au moins 3 % du produit intérieur brut annuel", "à au moins 1 % du produit intérieur brut annuel"),
		loi("lru-2007", dRecherche, "CADRE", "2007-08-10", "Parlement (loi n° 2007-1199)",
			"L'autonomie des universités",
			"Loi relative aux libertés et responsabilités des universités.",
			"JORFTEXT000000824315", "relative aux libertés et responsabilités des universités"),
		loi("ore-2018", dRecherche, "CADRE", "2018-03-08", "Parlement (loi n° 2018-166)",
			"L'orientation et la réussite des étudiants",
			"Loi relative à l'orientation et à la réussite des étudiants, qui encadre l'accès à la première année du premier cycle.",
			"JORFTEXT000036683777", "relative à l'orientation et à la réussite des étudiants"),
		senat("senat-recherche-lpr-2026", dRecherche, "CONTROLE", "323", "2025-11-06", "jean-francois-rapin", "Recherche et enseignement supérieur",
			"La programmation de la recherche poursuivie, mais des secteurs stratégiques en recul",
			"Le rapport juge que la loi de programmation a engagé un réinvestissement dans la recherche publique, confirmé en 2026 ; il relève que les crédits du programme 190 ne permettent pas d'atteindre l'objectif de soutien à la recherche aéronautique civile.",
			"a permis d'engager une dynamique de réinvestissement dans la recherche publique", "ne permettent pas d'atteindre l'objectif de soutien à la recherche aéronautique civile"),
		senat("senat-droits-inscription-2026", dRecherche, "CONTROLE", "323", "2025-11-06", "jean-francois-rapin", "Recherche et enseignement supérieur",
			"Droits d'inscription : 1,9 % des recettes des établissements",
			"Les droits d'inscription représentaient 1,9 % des recettes des établissements d'enseignement supérieur en 2025 ; le rapporteur spécial propose de les moduler selon le revenu du foyer fiscal de l'étudiant.",
			"ils ne représentaient ainsi qu'1,9 % du total des recettes"),
		senat("senat-boursiers-2026", dRecherche, "CONTROLE", "323", "2025-11-06", "jean-francois-rapin", "Recherche et enseignement supérieur",
			"662 000 étudiants boursiers, l'effectif le plus faible depuis 2015",
			"Les crédits des bourses baissent de 1,5 % en 2026, à 2,32 Md€ ; 662 000 étudiants sont boursiers en 2024-2025, le plus faible effectif depuis la rentrée 2015, faute de réévaluation du barème selon le rapport.",
			"On dénombre 662 000 étudiants boursiers en 2024-2025 : cet effectif est le plus faible constaté depuis la rentrée 2015"),
		senat("senat-effectifs-etudiants-2026", dRecherche, "SITUATION", "323", "2025-11-06", "jean-francois-rapin", "Recherche et enseignement supérieur",
			"Effectifs étudiants : + 15 % en dix ans",
			"Au cours des dix dernières années, les effectifs étudiants de l'enseignement supérieur, tous établissements et filières confondus, ont augmenté de 15 %.",
			"toutes filières confondues, ont augmenté de 15 %"),

		// Logement, hébergement et territoires.
		loi("sru-2000", dLogement, "CADRE", "2000-12-13", "Parlement (loi n° 2000-1208)",
			"Solidarité et renouvellement urbains",
			"Loi relative à la solidarité et au renouvellement urbains.",
			"JORFTEXT000000207538", "relative à la solidarité et au renouvellement urbains"),
		loi("elan-2018", dLogement, "CADRE", "2018-11-23", "Parlement (loi n° 2018-1021)",
			"Évolution du logement, de l'aménagement et du numérique",
			"Loi portant évolution du logement, de l'aménagement et du numérique.",
			"JORFTEXT000037639478", "portant évolution du logement, de l'aménagement et du numérique"),
		senat("senat-hebergement-enfants-2026", dLogement, "ENJEUX", "35-1", "2025-11-04", "sophie-primas", "Cohésion des territoires",
			"Plus de 2 150 enfants à la rue fin août 2025, selon l'UNICEF",
			"Le rapport cite le baromètre de l'UNICEF : plus de 2 150 enfants à la rue fin août 2025 ; il relève un risque de moindre qualité des places d'hébergement et de retour des nuitées hôtelières, alors que l'objectif de 203 000 places est maintenu.",
			"Plus de 2 150 enfants à la rue étaient recensés fin août 2025", "l'objectif de 203 000 places dans le parc est maintenu"),
		senat("senat-cohesion-baisse-2026", dLogement, "CONTROLE", "35-1", "2025-11-04", "sophie-primas", "Cohésion des territoires",
			"Cohésion des territoires : - 5,1 % hors inflation, et 11,68 Md€ de dépenses fiscales",
			"Les crédits passent de 23,1 Md€ à 22,2 Md€, une baisse de 5,1 % inflation déduite, liée surtout aux aides au logement et à la rénovation énergétique ; la politique est aussi financée par 11,68 Md€ de dépenses fiscales.",
			"de 5,1 % après correction de l'inflation", "11,68 milliards d'euros de dépenses fiscales"),
		senat("senat-apl-2026", dLogement, "CONTROLE", "35-1", "2025-11-04", "sophie-primas", "Cohésion des territoires",
			"Aides au logement : 5,7 millions de ménages, principal poste d'économies de l'État depuis 2017",
			"Le programme 109 (16,1 Md€) baisse de 587,1 M€ faute de revalorisation du barème ; 5,7 millions de ménages perçoivent une aide au logement, dont 87,2 % ont des revenus inférieurs au SMIC.",
			"Près de 5,7 millions de ménages bénéficient d'une aide au logement", "Les aides au logement constituent le principal poste d'économies du budget de l'État depuis 2017"),
		senat("senat-fnadt-2026", dLogement, "CONTROLE", "35-2", "2025-11-04", "bernard-delcros", "Cohésion des territoires",
			"Contrats de plan État-régions : 21 M€ manquent pour honorer les engagements",
			"Malgré la hausse des crédits de paiement du programme 112, le rapporteur spécial estime qu'il manque 21 M€ pour financer les restes à payer et les engagements contractuels de 2026 sur la section locale du Fonds national d'aménagement et de développement du territoire.",
			"Ce sont donc toujours 21 millions d'euros qui manquent"),

		// Outre-mer.
		loiArt("erom-2017-egalite-reelle", dOutreMer, "CADRE", "2017-02-28", "Parlement (loi n° 2017-256 de programmation relative à l'égalité réelle outre-mer)",
			"Le droit des populations des outre-mer à l'égalité réelle",
			"L'article 1er reconnaît aux populations des outre-mer le droit à l'égalité réelle au sein du peuple français et en fait une priorité de la Nation.",
			"JORFTEXT000034103762", "1", "le droit à l'égalité réelle au sein du peuple français"),
		loiArt("erom-2017-logements", dOutreMer, "CADRE", "2017-02-28", "Parlement (loi n° 2017-256, article 3)",
			"Objectif : 150 000 logements en dix ans",
			"La loi fixe l'objectif de construire 150 000 logements dans les outre-mer dans les dix ans suivant sa promulgation, soit d'ici 2027.",
			"JORFTEXT000034103762", "3", "la construction de 150 000 logements dans les outre-mer au cours des dix années"),
		senat("senat-outre-mer-collectivites-2026", dOutreMer, "ENJEUX", "320", "2025-11-04", "stephane-fouassin", "Outre-mer",
			"Des collectivités aux charges structurellement élevées",
			"Le rapport situe la difficulté des collectivités ultramarines dans des charges de fonctionnement structurellement élevées qui ne leur permettent pas de dégager une épargne suffisante pour investir sans l'État.",
			"Les difficultés des collectivités ultramarines résident dans leurs charges de fonctionnement structurellement élevées"),
		senat("senat-outre-mer-baisse-2026", dOutreMer, "CONTROLE", "320", "2025-11-04", "stephane-fouassin", "Outre-mer",
			"Mission Outre-mer : - 21,6 % en autorisations d'engagement",
			"Les crédits demandés s'élèvent à 2,91 Md€ en autorisations d'engagement et 2,83 Md€ en crédits de paiement, en baisse de 21,6 % et de 5,4 %, principalement du fait de la réforme des exonérations de cotisations propres aux outre-mer.",
			"soit une baisse de 21,6 % en AE et de 5,4 % en CP par rapport à la LFI 2025"),
		senat("senat-lodeom-2026", dOutreMer, "CONTROLE", "320", "2025-11-04", "stephane-fouassin", "Outre-mer",
			"Réforme des exonérations « LODEOM » : 350 M€ de coût pour les entreprises ultramarines",
			"La réforme prévue par le projet de loi de financement de la Sécurité sociale augmenterait de 5 % à 8 % la masse salariale des entreprises ultramarines, pour un coût total de 350 M€, que les rapporteurs jugent insoutenable.",
			"hausse de 5 % à 8 % de leur masse salariale, pour un coût total de 350 millions d'euros"),

		// Action extérieure et aide publique au développement.
		loiArt("loi-developpement-solidaire-2021", dExterieur, "CADRE", "2021-08-04", "Parlement (loi n° 2021-1031 de programmation relative au développement solidaire)",
			"Aide publique au développement : 0,55 % du revenu national brut en 2022, 0,7 % visé en 2025",
			"L'article 2 programme les crédits de la mission jusqu'en 2022, fixe l'aide publique au développement à 0,55 % du revenu national brut en 2022 et vise 0,7 % en 2025.",
			"JORFTEXT000043898536", "2", "0,55 % de son revenu national brut", "0,7 % du revenu national brut en 2025"),
		senat("senat-apd-remise-en-cause-2026", dExterieur, "ENJEUX", "34", "2025-11-06", "michel-canevet", "Aide publique au développement",
			"Une politique « remise en cause » dans son architecture et ses présupposés",
			"Les rapporteurs situent la baisse française dans un environnement international où l'aide au développement est remise en cause, dans son architecture financière comme dans ses présupposés politiques (solidarité internationale, multilatéralisme).",
			"où cette politique publique est remise en cause"),
		senat("senat-apd-baisse-2026", dExterieur, "CONTROLE", "34", "2025-11-06", "michel-canevet", "Aide publique au développement",
			"Aide au développement : - 35 % de crédits de paiement entre 2024 et 2025, - 16,1 % en 2026",
			"Entre les lois de finances pour 2024 et 2025, les crédits ont baissé de 28 % en autorisations d'engagement et de 35 % en crédits de paiement ; le projet pour 2026 prévoit encore - 16,1 % en crédits de paiement, à 3,67 Md€.",
			"de 28 % en autorisations d'engagements et de 35 % en crédits de paiement", "une baisse de 13,6 % en AE et de 16,1 % en CP"),
		senat("senat-apd-dispersion-2026", dExterieur, "CONTROLE", "34", "2025-11-06", "michel-canevet", "Aide publique au développement",
			"Une aide bilatérale dispersée dans 124 pays",
			"L'aide bilatérale française intervient dans 124 pays, contre 60 pour l'Allemagne ; l'objectif de concentrer 60 % de l'aide sur les pays les moins avancés et vulnérables n'est pas respecté.",
			"qui intervient dans 124 pays (contre 60 pour l'Allemagne)", "n'est pas respecté"),
		senat("senat-action-exterieure-emplois-2026", dExterieur, "CONTROLE", "31", "2025-11-19", "nathalie-goulet", "Action extérieure de l'État",
			"Diplomatie : l'objectif de 700 emplois supplémentaires de facto écarté",
			"Pour la première fois depuis 2021, le plafond d'emplois du ministère de l'Europe et des affaires étrangères reste stable ; l'ambition de créer 700 équivalents temps plein entre 2023 et 2027, issue des états généraux de la diplomatie, semble écartée.",
			"L'ambition de créer 700 ETP entre 2023 et 2027 semble, de facto, écartée"),

		// Sport, jeunesse et vie associative.
		loi("democratiser-sport-2022", dSport, "CADRE", "2022-03-02", "Parlement (loi n° 2022-296)",
			"Démocratiser le sport",
			"Loi visant à démocratiser le sport en France.",
			"JORFTEXT000045287568", "visant à démocratiser le sport en France"),
		loi("jop-2024-loi-2023", dSport, "CADRE", "2023-05-19", "Parlement (loi n° 2023-380)",
			"Les Jeux olympiques et paralympiques de 2024",
			"Loi relative aux Jeux olympiques et paralympiques de 2024.",
			"JORFTEXT000047561974", "relative aux jeux Olympiques et Paralympiques de 2024"),
		senat("senat-sport-premiere-contribution-2026", dSport, "CONTROLE", "330", "2025-11-13", "eric-jeansannetas", "Sport, jeunesse et vie associative",
			"La mission qui perd le plus de crédits, en proportion, dans le budget 2026",
			"En proportion de ses crédits de 2025, la mission est celle qui perd le plus dans le projet pour 2026 : le programme « jeunesse et vie associative » perd 26,1 %, le service civique 20 %, et le service national universel est supprimé.",
			"a perdu le plus de crédits dans le PLF pour 2026", "le service civique voit son enveloppe budgétaire réduite de 20 %", "suppression du service national universel"),
		senat("senat-pass-sport-2026", dSport, "CONTROLE", "330", "2025-11-13", "eric-jeansannetas", "Sport, jeunesse et vie associative",
			"Pass'Sport divisé par deux et réservé aux 14 ans et plus",
			"Les crédits du pass'Sport passent de 75 M€ à 39,2 M€ ; le dispositif ne serait ouvert qu'à partir de 14 ans ; le rapporteur spécial préférerait un recentrage sur les familles modestes plutôt que sur l'âge.",
			"qui passe de 75 millions d'euros à 39,2 millions d'euros"),
		senat("senat-jop-2030-2026", dSport, "CONTROLE", "330", "2025-11-13", "eric-jeansannetas", "Sport, jeunesse et vie associative",
			"Jeux d'hiver de 2030 : 400,7 M€ d'autorisations d'engagement demandées",
			"2026 est la première véritable année de préparation des Jeux olympiques et paralympiques de 2030 dans les Alpes françaises : 400,7 M€ en autorisations d'engagement et 54,8 M€ en crédits de paiement sont demandés.",
			"400,7 millions d'euros en AE et 54,8 millions d'euros en CP"),

		// Fonction publique et immobilier de l'État.
		loi("transformation-fonction-publique-2019", dFonction, "CADRE", "2019-08-06", "Parlement (loi n° 2019-828)",
			"La transformation de la fonction publique",
			"Loi de transformation de la fonction publique.",
			"JORFTEXT000038889182", "de transformation de la fonction publique"),
		senat("senat-fonction-publique-baisse-2026", dFonction, "CONTROLE", "314", "2025-11-13", "claude-nougein", "Transformation et fonction publiques",
			"Transformation et fonction publiques : - 45,8 % en autorisations d'engagement",
			"Les crédits baissent de 45,8 % en autorisations d'engagement, à 543,6 M€, surtout parce que la rénovation des 36 cités administratives s'est achevée en 2025.",
			"une baisse de - 45,8 % en AE, à 543,6 millions d'euros", "l'achèvement des chantiers de rénovation des 36 cités concernées"),
		senat("senat-fonciere-etat-2026", dFonction, "CONTROLE", "314", "2025-11-13", "claude-nougein", "Transformation et fonction publiques",
			"La foncière de l'État en attente d'un texte après sa censure",
			"La création d'une foncière de l'État, introduite par amendement au projet de loi de finances pour 2025, a été censurée par le Conseil constitutionnel comme cavalier budgétaire ; aucun texte ne l'a reprise depuis.",
			"censurée par le Conseil constitutionnel en tant que cavalier budgétaire"),

		// Économie et participations financières de l'État.
		loi("pacte-2019", dEconomie, "CADRE", "2019-05-22", "Parlement (loi n° 2019-486)",
			"Croissance et transformation des entreprises (loi PACTE)",
			"Loi relative à la croissance et la transformation des entreprises.",
			"JORFTEXT000038496102", "relative à la croissance et la transformation des entreprises"),
		loi("ordonnance-participations-2014", dEconomie, "CADRE", "2014-08-20", "Gouvernement (ordonnance n° 2014-948)",
			"La gouvernance des sociétés à participation publique",
			"Ordonnance relative à la gouvernance et aux opérations sur le capital des sociétés à participation publique.",
			"JORFTEXT000029391551", "relative à la gouvernance et aux opérations sur le capital des sociétés à participation publique"),
		senat("senat-economie-baisse-2026", dEconomie, "CONTROLE", "311", "2025-11-12", "frederique-espagnac", "Économie",
			"Mission Économie : - 27,1 % en autorisations d'engagement",
			"Les autorisations d'engagement baissent de 1,368 Md€ (- 27,1 %), principalement sur le programme 134 : compensation versée à La Poste pour ses missions de service public (- 125,3 M€) et compensation carbone des entreprises électro-intensives (- 269 M€).",
			"- 1,368 milliard d'euros (- 27,1 %)", "125,3 millions d'euros", "269 millions d'euros"),
		senat("senat-cessions-participations-2026", dEconomie, "CONTROLE", "321", "2025-11-13", "claude-raynal", "Participations financières de l'État",
			"3,2 Md€ de cessions d'actifs attendues en 2026, sur cinq opérations confidentielles",
			"Les recettes de cessions d'actifs du portefeuille de l'Agence des participations de l'État sont estimées à 3,2 Md€ en 2026, plus du triple de 2025 ; les cinq opérations correspondantes demeurent confidentielles.",
			"Les recettes de cessions sont en effet estimées à 3,2 milliards d'euros en 2026", "demeurent confidentielles"),
		senat("senat-dette-covid-participations-2026", dEconomie, "CONTROLE", "321", "2025-11-13", "claude-raynal", "Participations financières de l'État",
			"Fin du « schéma d'isolement de la dette covid », un « jeu d'écriture »",
			"Le Gouvernement abandonne le schéma d'isolement de la dette covid au sein du compte spécial, que le rapporteur spécial qualifie de jeu d'écriture sans portée réelle sur la dette de l'État.",
			"qui relevait d'un jeu d'écriture sans portée réelle sur la dette de l'État"),

		// France 2030 et plan de relance.
		loiArt("france-2030-renommage-2021", dFrance30, "CADRE", "2021-12-30", "Parlement (loi n° 2021-1900 de finances pour 2022, article 187)",
			"Les investissements d'avenir deviennent « Investir pour la France de 2030 »",
			"La loi de finances pour 2022 remplace, dans la loi de finances rectificative pour 2010 qui avait créé les investissements d'avenir, leur intitulé par « Investir pour la France de 2030 ».",
			"JORFTEXT000044637640", "187", "sont remplacés par les mots : « “ Investir pour la France de 2030 ” »"),
		loiArt("france-relance-suivi-2020", dFrance30, "CADRE", "2020-12-29", "Parlement (loi n° 2020-1721 de finances pour 2021, article 246)",
			"Un comité national de suivi du plan « France Relance »",
			"La loi de finances pour 2021, qui crée la mission « Plan de relance », institue un comité national de suivi du plan placé auprès du Premier ministre.",
			"JORFTEXT000042753580", "246", "Un comité national de suivi du plan « France Relance », placé auprès du Premier ministre"),
		senat("senat-france-2030-deploiement-2026", dFrance30, "CONTROLE", "316", "2025-10-29", "laurent-somon", "Investir pour la France de 2030",
			"France 2030 : 40 Md€ d'aides attribuées, 14 Md€ versés sur 54 Md€",
			"Sur une enveloppe totale de 54 Md€, les opérateurs du plan (Ademe, Agence nationale de la recherche, Bpifrance, Caisse des dépôts) ont attribué 40 Md€ d'aides et versé 14 Md€ aux bénéficiaires finaux après cinq exercices.",
			"D'ATTRIBUER 40 MILLIARDS D'EUROS D'AIDES ET DE VERSER AUX BÉNÉFICIAIRES FINAUX 14 MILLIARDS D'EUROS", "l'enveloppe pluriannuelle totale du plan France 2030 atteint 54 milliards d'euros"),
		senat("senat-france-2030-information-2026", dFrance30, "CONTROLE", "316", "2025-10-29", "laurent-somon", "Investir pour la France de 2030",
			"Une information du Parlement jugée insuffisante",
			"Les rapporteurs spéciaux jugent insuffisantes les informations transmises au Parlement sur le déploiement du plan ; l'objectif « décarbonation de l'industrie » n'a vu que 36 % de ses aides attribuées.",
			"LES INFORMATIONS TRANSMISES AU PARLEMENT SUR LE DÉPLOIEMENT DU PLAN RESTENT INSUFFISANTES", "n'ont été attribuées qu'à hauteur de 36 %"),
		senat("senat-france-2030-territoires-2026", dFrance30, "SITUATION", "316", "2025-10-29", "laurent-somon", "Investir pour la France de 2030",
			"5 500 bénéficiaires, dont 24 Md€ d'aides attribuées en Île-de-France",
			"Au 30 juin 2025, le plan a soutenu 5 500 bénéficiaires finaux ; l'Île-de-France concentre 24 Md€ d'aides attribuées, et cinq autres régions métropolitaines plus de 2 Md€ chacune.",
			"les aides du plan avaient permis de soutenir 5 500 bénéficiaires finaux", "Île-de-France qui a bénéficié de 24 milliards d'euros d'aides attribuées"),

		// Agriculture.
		loi("egalim-2018", dAgri, "CADRE", "2018-10-30", "Parlement (loi n° 2018-938, dite EGalim)",
			"Relations commerciales agricoles et alimentation durable (EGalim)",
			"Loi pour l'équilibre des relations commerciales dans le secteur agricole et alimentaire et une alimentation saine, durable et accessible à tous.",
			"JORFTEXT000037547946", "pour l'équilibre des relations commerciales dans le secteur agricole et alimentaire"),
		loiArt("loa-2025-souverainete-alimentaire", dAgri, "CADRE", "2025-03-24", "Parlement (loi n° 2025-268 d'orientation pour la souveraineté alimentaire et le renouvellement des générations en agriculture)",
			"L'agriculture « d'intérêt général majeur » au titre de la souveraineté alimentaire",
			"L'article 1er inscrit dans le code rural que la protection, la valorisation et le développement de l'agriculture et de la pêche sont d'intérêt général majeur en tant qu'ils garantissent la souveraineté alimentaire de la Nation.",
			"JORFTEXT000051368091", "1", "sont d'intérêt général majeur en tant qu'ils garantissent la souveraineté alimentaire de la Nation"),
		senat("senat-agriculture-baisse-2026", dAgri, "CONTROLE", "33", "2025-11-12", "christian-klinger", "Agriculture, alimentation, forêt et affaires rurales",
			"Mission Agriculture : - 11,59 % en autorisations d'engagement",
			"Le projet déposé prévoit une baisse de 11,59 % des autorisations d'engagement et de 4,98 % des crédits de paiement, portée surtout par les actions jugées pilotables par le ministère.",
			"une baisse de 11,59 % des autorisations d'engagement et de 4,98 % des crédits de paiement"),
		senat("senat-planification-ecologique-agriculture-2026", dAgri, "CONTROLE", "33", "2025-11-12", "christian-klinger", "Agriculture, alimentation, forêt et affaires rurales",
			"Planification écologique agricole : de 1,3 Md€ en 2024 à 143 M€ en 2026",
			"Les actions « planification écologique » créées en 2024 avec 1,3 Md€ ont été ramenées à 491 M€ en 2025 et 143 M€ demandés pour 2026 : en deux ans, - 67 % en autorisations d'engagement et - 59 % en crédits de paiement.",
			"ramené en 2025 à 491 millions d'euros et réduit pour 2026 à 143 millions d'euros"),
	)
}
